### ISSUE TITLE
Failed to change user ownership

### ISSUE THREAD

**Issue by androsland** [QoboLtd/project-template-wordpress#45]
Warning: chown(): Unable to find uid for nginx in /var/www/abxglobal.com/vendor/qobo/phake
-builder/lib/FileSystem.php on line 156
PHP Warning:  chown(): Unable to find uid for nginx in /var/www/abxglobal.com/vendor/qobo/
phake-builder/lib/FileSystem.php on line 156

**Comment by mamchenkov** [comment]
@androsland 

This means that you are trying to run ```chown``` command with a user that doesn't exist on your system.  In this case, nginx.  This user is usually created when installing Nginx web server package.  Either install that, or change the user parameter.
