### ISSUE TITLE
Error on media upload when Compress PNG WP plugin is enabled 

### ISSUE THREAD

**Issue by flangofas** [QoboLtd/project-template-wordpress#53]
When I try to upload new media, I get the following error message: 
> An error occurred in the upload. Please try again later.
Nevertheless, the media gets uploaded on page refresh.

If I disable following option in Settings -> Media.
> Automatically shrink files on upload?

Then I can upload without a problem.

Plugin's key is the default one.

**Comment by neophytosconst** [comment]
@flangofas Can you try with another key? Its very likely that the quota has been exceeded and may be causing this.

**Comment by flangofas** [comment]
@neophytosconst Sure. I'll give it a shot.

**Comment by flangofas** [comment]
Closing this issue. The problem occurs because we exceeded the limit of TinyPNG plugin.
:+1: @neophytosconst
